intervenant_index:
    path:     /
    defaults: { _controller: "EcoleBundle:Intervenant:index" }
    methods:  GET

intervenant_show:
    path:     /{id}/show
    defaults: { _controller: "EcoleBundle:Intervenant:show" }
    methods:  GET

intervenant_new:
    path:     /new
    defaults: { _controller: "EcoleBundle:Intervenant:new" }
    methods:  [GET, POST]

intervenant_edit:
    path:     /{id}/edit
    defaults: { _controller: "EcoleBundle:Intervenant:edit" }
    methods:  [GET, POST]

intervenant_delete:
    path:     /{id}/delete
    defaults: { _controller: "EcoleBundle:Intervenant:delete" }
    methods:  DELETE
