<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3j7p63v\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3j7p63v/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container3j7p63v.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container3j7p63v\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container3j7p63v\appDevDebugProjectContainer(array(
    'container.build_hash' => '3j7p63v',
    'container.build_id' => '45aef73a',
    'container.build_time' => 1515276815,
));
